version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.purpurmc.purpur:purpur-api"

  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "shards"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.purpurmc.purpur:purpur-api"
