# ---Sentry/GlitchTip---
sentryEnabled: false
sentryDsn: https://abcdefghijklmnopqrstuvxyz.ingest.sentry.io/123456789

# ---Postgres---
postgresUrl: "jdbc:postgresql://localhost:5432/diamond"
postgresUser: "postgres"
postgresPassword: "postgrespassword"
postgresTable: "diamond"
