# ---Sentry (or compatible services like GlitchTip)---
sentryEnabled: false
sentryDsn: "Sentry(-compatible) DSN"

# ---Postgres---
postgresUrl: "jdbc:postgresql://localhost:5432/diamond"
postgresUser: "postgres"
postgresPassword: "postgrespassword"
postgresTable: "diamond"
