name: '${project.artifactId}'
version: '${project.version}'
main: io.github.andromdaa.Plugin
api-version: 1.16
commands:
   bank:
      description: Your description
      usage: /<command>
softdepend: [Vault]
