name: DiamondBank-OG
version: '${version}'
main: net.trueog.diamondbankog.DiamondBankOG
api-version: '${apiVersion}'
commands:
  deposit:
    description: Deposit diamonds into your bank
    usage: /deposit <diamonds> <shards (optional)> or /deposit all
  withdraw:
    description: Withdraw diamonds from your bank
    usage: /withdraw <diamonds> <shards (optional)> or /withdraw all
  setbankbalance:
    description: Set the bank balance of a player
    usage: /setbankbalance <player name or player uuid> <shards>
  setbankbal:
    description: Set the bank balance of a player
    usage: /setbankbal <player name or player uuid> <shards>
  pay:
    description: Pay a player
    usage: /pay <player name or player uuid> <diamonds> <shards (optional)>
  balancetop:
    description: Show the balancetop
    usage: /balancetop <page number (optional)>
  baltop:
    description: Show the balancetop
    usage: /baltop <page number (optional)>
  balance:
    description: Get your or someone else's balance
    usage: /balance or /balance <player name or player uuid>
  bal:
    description: Get your or someone else's balance
    usage: /bal or /bal <player name or player uuid>
  diamondbankreload:
    description: Reload the config
    usage: /diamondbankreload

# So we can overwrite Essentials' commands
softdepend: [ Essentials ]