name: DiamondBank-OG
version: '${version}'
main: net.trueog.diamondbankog.DiamondBankOG
api-version: '${apiVersion}'
commands:
  bank:
    description: Your description
    usage: /<command>
  deposit:
    description: Deposit diamonds into your bank
    usage: /deposit <amount> or /deposit all
  withdraw:
    description: Withdraw diamonds from your bank
    usage: /withdraw <amount> or /withdraw all
  setbankbalance:
    description: Set the bank balance of a player
    usage: /setbankbalance <playername> <amount> or /setbankbalance <playeruuid> <amount>
  setbankbal:
    description: Set the bank balance of a player
    usage: /setbankbal <player> <amount> or /setbankbal <playeruuid> <amount>
  pay:
    description: Pay a player
    usage: /pay <player> <amount>
